auth:
  # Login user.
  # Default: $USER
  user: ""

  # Password of the login user.
  # Default: ""
  password: ""

  # Ask for password of login user.
  # Default: false
  ask-pass: false

  # File that contains 'username:password'.
  # Default: ""
  file: ""

  # Identity files of pubkey authentication.
  # Default:
  #   - $HOME/.ssh/id_rsa
  #   - $HOME/.ssh/id_dsa
  identity-files: []

  # Passphrase of the identity files.
  # Default: ""
  passphrase: ""

hosts:
  # File containing target hosts (format: one host per line).
  # Default: ""
  file: ""

  # Port of target hosts.
  # Default: 22
  port: 22

run:
  # Use sudo to execute command/script or fetch files/dirs.
  # Default: false
  sudo: false

  # Run via sudo as this user.
  # Default: root
  as-user: root

  # Specify i18n envs when execute command/script.
  # Default: origin i18n value on target hosts
  lang: ""

  # Number of concurrent connections.
  # Default: 1
  concurrency: 1

output:
  # File to which messages are output.
  # Default: ""
  file: ""

  # Output messages in json format.
  # Default: false
  json: false

  # Show debug messages.
  # Default: false
  verbose: false

  # Do not output messages to screen (except error messages).
  # Default: false
  quite: false

timeout:
  # Timeout seconds for connecting each target host.
  # Default: 10 (seconds)
  conn: 10

  # Timeout seconds for executing commands/script on each target host.
  # Default: 0
  command: 0

  # Timeout seconds for running the current gossh task.
  # Default: 0
  task: 0

proxy:
  # Proxy server address, and it will enable proxy if it not null.
  # Default: ""
  server: ""

  # Proxy server port.
  # Default: 22
  port: 22

  # Login user for proxy.
  # Default: value of 'auth.user'
  user: ""

  # Password for proxy.
  # Default: value of 'auth.password'
  password: ""

  # Identity files for proxy.
  # Default: value of 'auth.identity-files'
  identity-files: []

  # Passphrase of the identity files for proxy.
  # Default: value of 'auth.passphrase'
  passphrase: ""
