auth:
  # login user (default is $USER).
  user: ""
  # password of the login user.
  password: ""
  # file that contains 'username:password'.
  file: ""
  # use pubkey authentication.
  pubkey: false
  # identity files.
  # default:
  #   - $HOME/.ssh/id_rsa
  #   - $HOME/.ssh/id_dsa
  identity-file:
    -

hosts:
  # file containing target hosts (format: one host per line).
  file: ""
  # port of target hosts.
  # default: 22
  port: 22

run:
  # use sudo to execute the command.
  sudo: false
  # run via sudo as this user.
  # default: root
  as-user: root
  # specify i18n envs when execute command/script.
  lang: ""
  # number of concurrent connections.
  # default: 1
  concurrency: 1

output:
  # file to which messages are output.
  file: ""
  # output messages in json format
  json: false
  # show debug messages.
  verbose: false
  # do not output messages to screen (except error messages).
  quite: false

timeout:
  # timeout for connecting each remote host.
  # default: 10 (seconds)
  conn: 10
  # timeout for executing commands/script on each remote host.
  command: 0
  # timeout for the current gossh task.
  task: 0
